<!DOCTYPE html>
<html>
    <head>
        <title>Unreal City</title>
        <style>
            @import url('https://fonts.googleapis.com/css?family=Oswald|Roboto&display=swap');

            h1 {
                text-transform: uppercase;
                font-family: 'Oswald', serif;
                font-size: 4em;
                margin-top: 1px;
                margin-bottom: 6px;
                text-align: center;
            }

            body {
                padding-top: 150px;
                padding-left: 1.5em;
                padding-right: 1.5em;
                background-color: #fff;
                font-family: 'Roboto', serif;
                color: #222;
                -webkit-user-select: none;
            }

            .header {
                position: absolute;
                background-color: #020202;
                padding: 1.2em;
                top: 0;
                left: 0;
                right: 0;
                color: #ffffff;
                text-align: center;
            }

            .menu-button {
                position: absolute;
                height: 50px;
                width: 50px;
                border-radius: 100px;
                box-shadow: 0 0 7px #000;  
                bottom: -25px;
                left: 50%;
                margin-left: -25px;
                background-color: #fff;
                color: black;
                line-height: 50px;
                vertical-align: center;
                font-size: 30px;
            }

            .menu-button:after {
                content: "⮟";
            }

            .active:after {
                content: "⮝";
            }

            .menu-button:hover {
                box-shadow: 0 0 10px #000;
                transition: 0.4s;
            }

            .menu-chevron {
                position: absolute;
                border-width: 0 0 2px 2px;
                border-style: solid;
                height: 15px;
                width: 15px;
                transform: rotate(-45deg);
                left: 16px;
                top: 12px;
            }

            .content {
                padding: 0 18px;
                display: none;
                overflow: hidden;
                background-color: #020202;
                text-align: center;
                max-width: 1000px;
                margin:auto;
                margin-bottom: 1.2em;
            }

            @media (max-width: 750px) {
                .header {
                    font-size: 85%;
                }
            }

            @media (max-width: 650px) {
                .header {
                    font-size: 75%;
                }
            }

            .columns {
                display: flex;
                flex-wrap: wrap;
                justify-content: center;
                align-items: flex-start;
            }

            .card {
                margin: 1em;
                width: 20em;
                padding: 2em;
                display: inline-flex;
                flex-direction: column;
                align-items: center;
            }

            .portrait {

            }

            .story {
                text-align: justify;
                white-space: pre-wrap;
                padding-top: 2em;
                padding-left: 0.7em;
                padding-right: 0.7em;
            }

            .fleuron {
                padding-top: 0.2em;
                font-size: 2em;
                text-align: center;
            }

            img {
                max-width: 20em;
                height: auto;
            }
        </style>
    </head>

    <body>
        <div class="header">
            <h1>Humans of an Unreal City</h1> 
            <div class="content">
                These stories were composed by OpenAI's GPT-2 writing model, which was given various prompts and asked to elaborate. Many of the results were gibberish. Several were borderline coherent. A few were inflected with weird beauty. My favourites are recorded here - some lightly edited, many entirely intact.<br><br>The accompanying photos were generated by the AI at thispersondoesnotexist.com. They are not real humans, but you can look into their eyes nonetheless. You can generate more humans by refreshing the page.
            </div>
            <div class="menu-button">
                <!-- &#11167 -->
                <!-- <div class="menu-chevron"></div> -->
            </div>
        </div>
        <div class="columns">
            <?php 
                const MAXIMUM_HUMANS = 12;
                $imgs = scandir('images');
                $stos = scandir('stories');
                $shortestArrayLength = min([count($imgs),count($stos)])-1;
                $possibles = range(2,$shortestArrayLength);
                shuffle($possibles);
                for($i=0; $i<MAXIMUM_HUMANS; $i++){
                    $humanIndex = $possibles[$i];
                    ?>
                        <div class="card">
                            <div class="portrait">
                            <img src="images/<?= $imgs[$humanIndex]?>"/>
                            </div>
                            <div class="story"><?php
                                echo file_get_contents ("stories/{$stos[$humanIndex]}");
                            ?><div class="fleuron">&#128607;
                            </div>
                        </div>
                        </div>
                    <?php
                }
            ?>
        </div>
            
        </div>

        <script>
            var coll = document.getElementsByClassName("menu-button");
            var i;

            for (i = 0; i < coll.length; i++) {
            coll[i].addEventListener("click", function() {
                this.classList.toggle("active");
                var content = this.previousElementSibling;
                if (content.style.display === "block") {
                    content.style.display = "none";
                  } else {
                    content.style.display = "block";
                  }
            });
            }
        </script>

    </body>

</html>